package com.twistlet.vettel.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name="authority"
)
public class Authority  implements java.io.Serializable {


     private String authority;
     private String description;

    public Authority() {
    }

    public Authority(String authority, String description) {
       this.authority = authority;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="authority", unique=true, nullable=false, length=50)
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    
    @Column(name="description", nullable=false, length=120)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


