package com.twistlet.vettel.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PersonAuthority generated by hbm2java
 */
@Entity
@Table(name="person_authority"
)
public class PersonAuthority  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String authority;

    public PersonAuthority() {
    }

    public PersonAuthority(String username, String authority) {
       this.username = username;
       this.authority = authority;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=80)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="authority", nullable=false, length=50)
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }




}


