package com.twistlet.vettel.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
)
public class Person  implements java.io.Serializable {


     private String username;
     private String name;
     private String password;
     private byte enabled;
     private Set<PersonAuthority> personAuthorities = new HashSet<PersonAuthority>(0);

    public Person() {
    }

	
    public Person(String username, String name, String password, byte enabled) {
        this.username = username;
        this.name = name;
        this.password = password;
        this.enabled = enabled;
    }
    public Person(String username, String name, String password, byte enabled, Set<PersonAuthority> personAuthorities) {
       this.username = username;
       this.name = name;
       this.password = password;
       this.enabled = enabled;
       this.personAuthorities = personAuthorities;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=80)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="name", nullable=false, length=120)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="password", nullable=false, length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="enabled", nullable=false)
    public byte getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(byte enabled) {
        this.enabled = enabled;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set<PersonAuthority> getPersonAuthorities() {
        return this.personAuthorities;
    }
    
    public void setPersonAuthorities(Set<PersonAuthority> personAuthorities) {
        this.personAuthorities = personAuthorities;
    }




}


