package com.twistlet.vettel.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PersonAuthority generated by hbm2java
 */
@Entity
@Table(name="person_authority"
    , uniqueConstraints = @UniqueConstraint(columnNames={"username", "authority"}) 
)
public class PersonAuthority  implements java.io.Serializable {


     private Integer id;
     private Authority authority;
     private Person person;

    public PersonAuthority() {
    }

    public PersonAuthority(Authority authority, Person person) {
       this.authority = authority;
       this.person = person;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="authority", nullable=false)
    public Authority getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(Authority authority) {
        this.authority = authority;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }




}


